### ISSUE TITLE
KeyError in fragments

### ISSUE THREAD

**Issue by markedwards** [mirumee/ariadne-codegen#173]
Running into a crash that seems to be related to fragment types:

```
gidev@e2f10272476c:/api$ ariadne-codegen
 [2023-06-17 08:50:51,988] [6114] [level=INFO] [httpx] HTTP Request: POST https://.../graphql/ "HTTP/1.1 200 OK" 
Selected strategy: client
Using schema from 'https://.../graphql/'.
Reading queries from 'queries/'.
Using 'graphql_client' as package name.
Generating package into 'api'.
Using 'Client' as client name.
Using 'AsyncBaseClient' as base client class.
Coping base client class from '/home/gidev/.local/lib/python3.10/site-packages/ariadne_codegen/client_generators/dependencies/async_base_client.py'.
Generating enums into 'enums.py'.
Generating inputs into 'input_types.py'.
Generating fragments into 'fragments.py'.
Including comments.
Converting fields and arguments name to snake case.
Generating async client.
No files to copy.
No plugin is being used.
Traceback (most recent call last):
  File "/home/gidev/.local/bin/ariadne-codegen", line 8, in <module>
    sys.exit(main())
  File "/home/gidev/.local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/gidev/.local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/gidev/.local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/gidev/.local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/gidev/.local/lib/python3.10/site-packages/ariadne_codegen/main.py", line 33, in main
    client(config_dict)
  File "/home/gidev/.local/lib/python3.10/site-packages/ariadne_codegen/main.py", line 88, in client
    package_generator.add_operation(query)
  File "/home/gidev/.local/lib/python3.10/site-packages/ariadne_codegen/client_generators/package.py", line 198, in add_operation
    query_types_generator = ResultTypesGenerator(
  File "/home/gidev/.local/lib/python3.10/site-packages/ariadne_codegen/client_generators/result_types.py", line 118, in __init__
    self._class_defs = self._parse_type_definition(
  File "/home/gidev/.local/lib/python3.10/site-packages/ariadne_codegen/client_generators/result_types.py", line 266, in _parse_type_definition
    self._parse_field_selection_set_types(
  File "/home/gidev/.local/lib/python3.10/site-packages/ariadne_codegen/client_generators/result_types.py", line 449, in _parse_field_selection_set_types
    self._parse_type_definition(
  File "/home/gidev/.local/lib/python3.10/site-packages/ariadne_codegen/client_generators/result_types.py", line 217, in _parse_type_definition
    resolved_selection_set, fragments = self._resolve_selection_set(
  File "/home/gidev/.local/lib/python3.10/site-packages/ariadne_codegen/client_generators/result_types.py", line 296, in _resolve_selection_set
    fragment_def = self.fragments_definitions[selection.name.value]
KeyError: 'attributeFields'
```

**Comment by markedwards** [comment]
This seems to happen when the fragments are not in the `queries_path`.  Maybe nicer error would help debug?

Otherwise, this should just be closed as it was my mistake.

**Comment by mat-sop** [comment]
Hey, You're right we should return more descriptive exception that just `KeyError`
