### ISSUE TITLE
Error when generating Python client for DataHub graphql files

### ISSUE THREAD

**Issue by J0hnG4lt** [mirumee/ariadne-codegen#175]
# Error when generating Python client for DataHub graphql files

## Traceback

```console
(datahub) georvic@georvic-IdeaPad-3-15ITL6:~/repos/datahub-metadata$ ariadne-codegen
Selected strategy: Strategy.CLIENT
Using schema from '/home/georvic/repos/datahub/datahub-graphql-core/src/main/resources'.
Reading queries from '/home/georvic/repos/datahub/datahub-web-react/src/graphql'.
Using 'graphql_client' as package name.
Generating package into '/home/georvic/repos/datahub-metadata'.
Using 'Client' as client name.
Using 'AsyncBaseClient' as base client class.
Coping base client class from '/home/georvic/anaconda3/envs/datahub-python-3-9/lib/python3.11/site-packages/ariadne_codegen/client_generators/dependencies/async_base_client.py'.
Generating enums into 'enums.py'.
Generating inputs into 'input_types.py'.
Generating fragments into 'fragments.py'.
Including comments.
Converting fields and arguments name to snake case.
Generating async client.
No files to copy.
No plugin is being used.
Traceback (most recent call last):
  File "/home/georvic/anaconda3/envs/datahub-python-3-9/lib/python3.11/site-packages/ariadne_codegen/client_generators/result_types.py", line 359, in _get_field_from_schema
    return cast(GraphQLObjectType, self.schema.type_map[type_name]).fields[
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'lineage'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/georvic/anaconda3/envs/datahub-python-3-9/bin/ariadne-codegen", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/georvic/anaconda3/envs/datahub-python-3-9/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/georvic/anaconda3/envs/datahub-python-3-9/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/georvic/anaconda3/envs/datahub-python-3-9/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/georvic/anaconda3/envs/datahub-python-3-9/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/georvic/anaconda3/envs/datahub-python-3-9/lib/python3.11/site-packages/ariadne_codegen/main.py", line 33, in main
    client(config_dict)
  File "/home/georvic/anaconda3/envs/datahub-python-3-9/lib/python3.11/site-packages/ariadne_codegen/main.py", line 89, in client
    generated_files = package_generator.generate()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/georvic/anaconda3/envs/datahub-python-3-9/lib/python3.11/site-packages/ariadne_codegen/client_generators/package.py", line 175, in generate
    self._generate_fragments()
  File "/home/georvic/anaconda3/envs/datahub-python-3-9/lib/python3.11/site-packages/ariadne_codegen/client_generators/package.py", line 336, in _generate_fragments
    module = generator.generate()
             ^^^^^^^^^^^^^^^^^^^^
  File "/home/georvic/anaconda3/envs/datahub-python-3-9/lib/python3.11/site-packages/ariadne_codegen/client_generators/fragments.py", line 46, in generate
    generator = ResultTypesGenerator(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/home/georvic/anaconda3/envs/datahub-python-3-9/lib/python3.11/site-packages/ariadne_codegen/client_generators/result_types.py", line 118, in __init__
    self._class_defs = self._parse_type_definition(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/georvic/anaconda3/envs/datahub-python-3-9/lib/python3.11/site-packages/ariadne_codegen/client_generators/result_types.py", line 266, in _parse_type_definition
    self._parse_field_selection_set_types(
  File "/home/georvic/anaconda3/envs/datahub-python-3-9/lib/python3.11/site-packages/ariadne_codegen/client_generators/result_types.py", line 449, in _parse_field_selection_set_types
    self._parse_type_definition(
  File "/home/georvic/anaconda3/envs/datahub-python-3-9/lib/python3.11/site-packages/ariadne_codegen/client_generators/result_types.py", line 266, in _parse_type_definition
    self._parse_field_selection_set_types(
  File "/home/georvic/anaconda3/envs/datahub-python-3-9/lib/python3.11/site-packages/ariadne_codegen/client_generators/result_types.py", line 449, in _parse_field_selection_set_types
    self._parse_type_definition(
  File "/home/georvic/anaconda3/envs/datahub-python-3-9/lib/python3.11/site-packages/ariadne_codegen/client_generators/result_types.py", line 243, in _parse_type_definition
    field_definition = self._get_field_from_schema(type_name, field.name.value)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/georvic/anaconda3/envs/datahub-python-3-9/lib/python3.11/site-packages/ariadne_codegen/client_generators/result_types.py", line 367, in _get_field_from_schema
    raise ParsingError(
ariadne_codegen.exceptions.ParsingError: Field lineage not found in type Entity.
```

This is the config file used:

```toml
[tool.ariadne-codegen]
schema_path = "/home/georvic/repos/datahub/datahub-graphql-core/src/main/resources"
queries_path = "/home/georvic/repos/datahub/datahub-web-react/src/graphql"
```

Here are the files:

https://github.com/datahub-project/datahub/tree/master/datahub-graphql-core/src/main/resources
https://github.com/datahub-project/datahub/tree/master/datahub-web-react/src/graphql

Versions:

```console
(datahub) georvic@georvic-IdeaPad-3-15ITL6:~/repos/datahub-metadata$ ariadne-codegen --version
ariadne-codegen, version 0.7.1
(datahub) georvic@georvic-IdeaPad-3-15ITL6:~/repos/datahub-metadata$ python --version
Python 3.11.3
```

**Comment by J0hnG4lt** [comment]
Placing the breakpoint here

![imagen](https://github.com/mirumee/ariadne-codegen/assets/10814689/16da5e4d-f30b-4150-8ccd-4d5a2ace7881)

I get the following:

![imagen](https://github.com/mirumee/ariadne-codegen/assets/10814689/0308a64d-44b7-47f3-9d2a-4824d7082364)

That fragment is here:

![imagen](https://github.com/mirumee/ariadne-codegen/assets/10814689/7debbf72-bb49-429e-9b9b-508d0afcf999)

It can be found here: https://github.com/datahub-project/datahub/blob/master/datahub-web-react/src/graphql/lineage.graphql#L293

**Comment by mat-sop** [comment]
Hey, It took some time, but we found what causes the problem - we don't properly handle spreads of fragments defined on subtype of field's interface type. I managed to replicate the issue on smaller example:
```gql
type Query {
  hello: BaseInterface!
}

interface BaseInterface {
  id: ID!
}

interface InterfaceA implements BaseInterface {
  id: ID!
  valueA: String!
}

type TypeA implements InterfaceA & BaseInterface {
  id: ID!
  valueA: String!
  another: String!
}
```
```gql
query testQuery {
  hello {
    ...fragmentA
  }
}

fragment fragmentA on InterfaceA {
  id
  valueA
  ... on TypeA {
    another
  }
}
```
