### ISSUE TITLE
Unexpected <EOF>

### ISSUE THREAD

**Issue by danieledwardgeorgehitchcock** [mirumee/ariadne-codegen#193]
When trying to generate a package using the following `pyproject.toml` file:

```toml
[tool.ariadne-codegen]
remote_schema_url = "https://rippleenergy.com/graphql"
queries_path = "src/ripple_energy/graphql/"
```

I get the following error:

```terminal
Traceback (most recent call last):
  File "C:\Users\danie\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\danie\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\danie\AppData\Local\hatch\env\virtual\ripple-energy\jAAfYL9X\ripple-energy\Scripts\ariadne-codegen.exe\__main__.py", line 7, in <module>
  File "C:\Users\danie\AppData\Local\hatch\env\virtual\ripple-energy\jAAfYL9X\ripple-energy\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\danie\AppData\Local\hatch\env\virtual\ripple-energy\jAAfYL9X\ripple-energy\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\danie\AppData\Local\hatch\env\virtual\ripple-energy\jAAfYL9X\ripple-energy\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\danie\AppData\Local\hatch\env\virtual\ripple-energy\jAAfYL9X\ripple-energy\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\danie\AppData\Local\hatch\env\virtual\ripple-energy\jAAfYL9X\ripple-energy\lib\site-packages\ariadne_codegen\main.py", line 33, in main
    client(config_dict)
  File "C:\Users\danie\AppData\Local\hatch\env\virtual\ripple-energy\jAAfYL9X\ripple-energy\lib\site-packages\ariadne_codegen\main.py", line 61, in client        
    definitions = get_graphql_queries(settings.queries_path)
  File "C:\Users\danie\AppData\Local\hatch\env\virtual\ripple-energy\jAAfYL9X\ripple-energy\lib\site-packages\ariadne_codegen\schema.py", line 38, in get_graphql_queries
    queries_ast = parse(queries_str)
  File "C:\Users\danie\AppData\Local\hatch\env\virtual\ripple-energy\jAAfYL9X\ripple-energy\lib\site-packages\graphql\language\parser.py", line 113, in parse     
    return parser.parse_document()
  File "C:\Users\danie\AppData\Local\hatch\env\virtual\ripple-energy\jAAfYL9X\ripple-energy\lib\site-packages\graphql\language\parser.py", line 241, in parse_document
    definitions=self.many(TokenKind.SOF, self.parse_definition, TokenKind.EOF),
  File "C:\Users\danie\AppData\Local\hatch\env\virtual\ripple-energy\jAAfYL9X\ripple-energy\lib\site-packages\graphql\language\parser.py", line 1149, in many     
    nodes = [parse_fn()]
  File "C:\Users\danie\AppData\Local\hatch\env\virtual\ripple-energy\jAAfYL9X\ripple-energy\lib\site-packages\graphql\language\parser.py", line 302, in parse_definition
    raise self.unexpected(keyword_token)
graphql.error.syntax_error.GraphQLSyntaxError: Syntax Error: Unexpected <EOF>.

GraphQL request:1:1
1 |
  | ^
```

Where am I going wrong? Or is this a bug?

**Comment by mat-sop** [comment]
Hey, it looks like queries read from `src/ripple_energy/graphql/` have incorrect syntax. There may be missing `}` or something similar. Hard to say without the actual content of these files.

**Comment by danieledwardgeorgehitchcock** [comment]
Hmm that's interesting.. I am able to run the generateschema script without error..

**Comment by mat-sop** [comment]
You're reading schema from remote, but to generate a client you also local files with queries/mutations/subscriptions.

**Comment by danieledwardgeorgehitchcock** [comment]
Thanks!

Could you refer me to any documentation relating to this?

**Comment by danieledwardgeorgehitchcock** [comment]
Here is a link to my repo / branch if that helps..? [GitHub](https://github.com/danieledwardgeorgehitchcock/ripple-energy/tree/ariadne)

**Comment by rafalp** [comment]
> Could you refer me to any documentation relating to this?

It's in first paragraph ;)

> Python code generator that takes graphql schema, **queries, mutations and subscriptions** and generates Python package with fully typed and asynchronous GraphQL client.

Ariadne Codegen is not an ORM or query builder for GraphQL. You need to point it at GraphQL schema and write the GraphQL queries yourself. We only convert them to Python code for you.

**Comment by danieledwardgeorgehitchcock** [comment]
Thanks!

Does the codegen accept introspection type schema's?

**Comment by rafalp** [comment]
Can you explain what you mean by "introspection type"? You can run it either against existing GraphQL API (as long as it supports schema introspection) or `schema.graphql` file.

**Comment by danieledwardgeorgehitchcock** [comment]
I have found a query which most tools used to query a GraphQL endpoint and retrieve an "introspected" schema:

```graphql
query IntrospectionQuery {
  __schema {
    queryType {
      name
    }
    mutationType {
      name
    }
    subscriptionType {
      name
    }
    types {
      ...FullType
    }
    directives {
      name
      description
      locations
      args {
        ...InputValue
      }
    }
  }
}

fragment FullType on __Type {
  kind
  name
  description
  fields(includeDeprecated: true) {
    name
    description
    args {
      ...InputValue
    }
    type {
      ...TypeRef
    }
    isDeprecated
    deprecationReason
  }
  inputFields {
    ...InputValue
  }
  interfaces {
    ...TypeRef
  }
  enumValues(includeDeprecated: true) {
    name
    description
    isDeprecated
    deprecationReason
  }
  possibleTypes {
    ...TypeRef
  }
}

fragment InputValue on __InputValue {
  name
  description
  type {
    ...TypeRef
  }
  defaultValue
}

fragment TypeRef on __Type {
  kind
  name
  ofType {
    kind
    name
    ofType {
      kind
      name
      ofType {
        kind
        name
        ofType {
          kind
          name
          ofType {
            kind
            name
            ofType {
              kind
              name
              ofType {
                kind
                name
              }
            }
          }
        }
      }
    }
  }
}
```

**Comment by rafalp** [comment]
If you specify schema as URL, codegen will do this for you automatically.

**Comment by danieledwardgeorgehitchcock** [comment]
See the original posting, that is what I did...

**Comment by rafalp** [comment]
Look at the queries part of [EXAMPLE.md](https://github.com/mirumee/ariadne-codegen/blob/main/EXAMPLE.md#queriesmutationssubscriptions-file) file. You need to create file like this yourself and configure codegen to read this file.

**Comment by rafalp** [comment]
Replace GraphQL with PostgreSQL. There's schema, but how can you get from it what database queries an app is going to execute? Codegen is not an ORM, just GraphQL queries to Python methods converter.

Please look at [test project our suite uses](https://github.com/mirumee/ariadne-codegen/tree/main/tests/main/clients/example). It has config file which points to [schema.graphql](https://github.com/mirumee/ariadne-codegen/blob/main/tests/main/clients/example/schema.graphql) and [queries.graphql](https://github.com/mirumee/ariadne-codegen/blob/main/tests/main/clients/example/schema.graphql) and codegen outputs [`example_client`](https://github.com/mirumee/ariadne-codegen/tree/main/tests/main/clients/example/expected_client).

**Comment by danieledwardgeorgehitchcock** [comment]
The introspection route lists the queries / mutations (not sure of fragments / unions  etc) with inputs and expected outputs.. isn't this a rudimentary schema in itself?

**Comment by rafalp** [comment]
Tangentially we are having some discussions and plans for adding ORM to client:

https://github.com/mirumee/ariadne-codegen/issues/132#issuecomment-1645494999

But its early days for this.

**Comment by danieledwardgeorgehitchcock** [comment]
Fantastic!

Thanks for the help guys! I now understand :-) - Closing in anticipation of the ORM
