### ISSUE TITLE
[httpx.ReadTimeout: The read operation timed out] on schema introspection

### ISSUE THREAD

**Issue by Anton-Shutik** [mirumee/ariadne-codegen#320]
Times out when trying to get schema via introspection. Seems like `httpx` has default [timeout of 5 seconds](https://www.python-httpx.org/advanced/timeouts/), it is not enough to load schema in the case.

```env
Python 3.9.13
ariadne-codegen==0.14.0
isort==5.13.2
black==24.8.0
```

```toml
[tool.ariadne-codegen]
remote_schema_url = "https://host/graphql.json"
remote_schema_headers = {"Token" = ""}
```

```python

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 233, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
    raise exc from None
  File "/usr/local/lib/python3.9/site-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
  File "/usr/local/lib/python3.9/site-packages/httpcore/_sync/connection.py", line 101, in handle_request
    return self._connection.handle_request(request)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_sync/http11.py", line 143, in handle_request
    raise exc
  File "/usr/local/lib/python3.9/site-packages/httpcore/_sync/http11.py", line 113, in handle_request
    ) = self._receive_response_headers(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_sync/http11.py", line 186, in _receive_response_headers
    event = self._receive_event(timeout=timeout)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_sync/http11.py", line 224, in _receive_event
    data = self._network_stream.read(
  File "/usr/local/lib/python3.9/site-packages/httpcore/_backends/sync.py", line 126, in read
    return self._sock.recv(max_bytes)
  File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ReadTimeout: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/ariadne-codegen", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/ariadne_codegen/main.py", line 37, in main
    client(config_dict)
  File "/usr/local/lib/python3.9/site-packages/ariadne_codegen/main.py", line 49, in client
    schema = get_graphql_schema_from_url(
  File "/usr/local/lib/python3.9/site-packages/ariadne_codegen/schema.py", line 69, in get_graphql_schema_from_url
    introspect_remote_schema(url=url, headers=headers, verify_ssl=verify_ssl),
  File "/usr/local/lib/python3.9/site-packages/ariadne_codegen/schema.py", line 78, in introspect_remote_schema
    response = httpx.post(
  File "/usr/local/lib/python3.9/site-packages/httpx/_api.py", line 319, in post
    return request(
  File "/usr/local/lib/python3.9/site-packages/httpx/_api.py", line 106, in request
    return client.request(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 827, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 914, in send
    response = self._send_handling_auth(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1015, in _send_single_request
    response = transport.handle_request(request)
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 233, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadTimeout: The read operation timed out

```

**Comment by Anton-Shutik** [comment]
I was able to fix it by manually adding `timeout=30` to the `post` call [here](https://github.com/mirumee/ariadne-codegen/blob/main/ariadne_codegen/schema.py#L82)

**Comment by Lur1an** [comment]
> I was able to fix it by manually adding `timeout=30` to the `post` call [here](https://github.com/mirumee/ariadne-codegen/blob/main/ariadne_codegen/schema.py#L82)

When working with remote schemas a higher default timeout value would be good, and also a `--http-timeout` parameter for the CLI.

**Comment by mzealey** [comment]
just run into this same issue - any chance for getting the PR merged?

**Comment by DamianCzajkowski** [comment]
Closed with: https://github.com/mirumee/ariadne-codegen/pull/369. Wait for 0.16 release!
