### ISSUE TITLE
AST error in generate client when using ClientForwardRefsPlugin

### ISSUE THREAD

**Issue by akshats1998** [mirumee/ariadne-codegen#324]
Hey! Currently when we import AriadneClient, it takes up about 400MB due to all the types, schemas. TO solve this we were hoping to use ClientForwardRefPlugin. However, on doing ariadne-codegen after setting the plugin we're getting the following error

```
Plugins to use: ariadne_codegen.contrib.no_reimports.NoReimportsPlugin,ariadne_codegen.contrib.client_forward_refs.ClientForwardRefsPlugin
Traceback (most recent call last):
  File "/Users/akshat/doppel/backend/functions/venv/bin/ariadne-codegen", line 8, in <module>
    sys.exit(main())
  File "/Users/akshat/doppel/backend/functions/venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/akshat/doppel/backend/functions/venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/akshat/doppel/backend/functions/venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/akshat/doppel/backend/functions/venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/akshat/doppel/backend/functions/venv/lib/python3.9/site-packages/ariadne_codegen/main.py", line 37, in main
    client(config_dict)
  File "/Users/akshat/doppel/backend/functions/venv/lib/python3.9/site-packages/ariadne_codegen/main.py", line 81, in client
    generated_files = package_generator.generate()
  File "/Users/akshat/doppel/backend/functions/venv/lib/python3.9/site-packages/ariadne_codegen/client_generators/package.py", line 171, in generate
    self._generate_client()
  File "/Users/akshat/doppel/backend/functions/venv/lib/python3.9/site-packages/ariadne_codegen/client_generators/package.py", line 259, in _generate_client
    ast_to_str(client_module, multiline_strings=True), self.queries_source
  File "/Users/akshat/doppel/backend/functions/venv/lib/python3.9/site-packages/ariadne_codegen/utils.py", line 27, in ast_to_str
    code = ast.unparse(ast_obj)
  File "/opt/homebrew/Cellar/python@3.9/3.9.19/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ast.py", line 1572, in unparse
    return unparser.visit(ast_obj)
  File "/opt/homebrew/Cellar/python@3.9/3.9.19/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ast.py", line 801, in visit
    self.traverse(node)
  File "/opt/homebrew/Cellar/python@3.9/3.9.19/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ast.py", line 795, in traverse
    super().visit(node)
  File "/opt/homebrew/Cellar/python@3.9/3.9.19/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/opt/homebrew/Cellar/python@3.9/3.9.19/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ast.py", line 816, in visit_Module
    self._write_docstring_and_traverse_body(node)
  File "/opt/homebrew/Cellar/python@3.9/3.9.19/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ast.py", line 809, in _write_docstring_and_traverse_body
    self.traverse(node.body)
  File "/opt/homebrew/Cellar/python@3.9/3.9.19/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ast.py", line 793, in traverse
    self.traverse(item)
  File "/opt/homebrew/Cellar/python@3.9/3.9.19/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ast.py", line 795, in traverse
    super().visit(node)
  File "/opt/homebrew/Cellar/python@3.9/3.9.19/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/opt/homebrew/Cellar/python@3.9/3.9.19/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ast.py", line 846, in visit_ImportFrom
    self.write("." * node.level)
    TypeError: can't multiply sequence by non-int of type 'NoneType'
    ```

**Comment by pkucmus** [comment]
Can you share some steps to reproduce and codegen version? I just used the plugin on Saleor's schema with no error. 

Python: 3.12.0
Codegen: 0.14.0

**Comment by akshats1998** [comment]
@pkucmus we are using Python: 3.9.20

**Comment by bombsimon** [comment]
I can't reproduce this. Can you add a reproducible example @akshats1998 or @lowzj?

```sh
› python -V
Python 3.9.20

› ariadne-codegen --version
ariadne-codegen, version 0.14.0

› cat pyproject.toml
[tool.ariadne-codegen]
schema_path = "schema.graphql"
queries_path = "queries.graphql"
include_comments = "none"
target_package_name = "client_forward_refs"
files_to_include = []
fragments_module_name = "client_forward_refs_fragments"
plugins = ["ariadne_codegen.contrib.client_forward_refs.ClientForwardRefsPlugin"]
```

- [`schema.graphql`](https://github.com/mirumee/ariadne-codegen/blob/11bfe35bd62b2489927e0e93c6891bccc29c7f37/tests/main/clients/client_forward_refs/schema.graphql)
- [`queries.graphql`](https://github.com/mirumee/ariadne-codegen/blob/11bfe35bd62b2489927e0e93c6891bccc29c7f37/tests/main/clients/client_forward_refs/queries.graphql)

```sh
› ariadne-codegen
Selected strategy: client
Using schema from 'schema.graphql'.
Reading queries from 'queries.graphql'.
Using 'client_forward_refs' as package name.
Generating package into '/Users/xxx/ariadne-codegen/tmp'.
Using 'Client' as client name.
Using 'AsyncBaseClient' as base client class.
Coping base client class from '/Users/xxx/ariadne-codegen/ariadne_codegen/client_generators/dependencies/async_base_client.py'.
Generating enums into 'enums.py'.
Generating inputs into 'input_types.py'.
Generating fragments into 'client_forward_refs_fragments.py'.
Comments type: none
Converting fields and arguments name to snake case.
Generating async client.
No files to copy.
Plugins to use: ariadne_codegen.contrib.client_forward_refs.ClientForwardRefsPlugin

Generated files:
  __init__.py
  async_base_client.py
  base_model.py
  client.py
  client_forward_refs_fragments.py
  enums.py
  exceptions.py
  get_animal_by_name.py
  get_animal_fragment_with_extra.py
  get_authenticated_user.py
  get_complex_scalar.py
  get_simple_scalar.py
  input_types.py
  list_animals.py
  list_strings_1.py
  list_strings_2.py
  list_strings_3.py
  list_strings_4.py
  list_type_a.py
  subscribe_strings.py
  unwrap_fragment.py
```

**Comment by bombsimon** [comment]
@akshats1998 Did you solve it or did you end up not using the plugin?

**Comment by akshats1998** [comment]
Hey @bombsimon we managed to use client forward refs after updating our pydantic version. We couldn't upgrade to v0.14 because of this issue https://github.com/mirumee/ariadne-codegen/issues/348 but we backported the plugin
