### ISSUE TITLE
An error is raised for Graphene's Date and DateTime scalars

### ISSUE THREAD

**Issue by lromanowicz** [mirumee/ariadne-codegen#74]
Given that we use Graphene.Date() scalar field looks like ariadne-codegen might not be able to "see" it as we're getting error like:

- `Argument type Date not found in schema`

PS. Same happens for DateTime scalar

Steps to reproduce:

1. Queries file:
```
  mutation EditRecipient(
    $dateOfBirth: Date
  ) {
      updateRecipient(
          dateOfBirth: $dateOfBirth
      )
  }
```

2. Schema file:
```
"""
The `Date` scalar type represents a Date
value as specified by
[iso8601](https://en.wikipedia.org/wiki/ISO_8601).
"""
scalar Date

type Query {
  test: String
}
type Mutation {
    updateRecipient(dateOfBirth: Date): String
}
```

3. Error raised:
```
Coping following files into package:
class EditRecipient(BaseModel):
    updateRecipient: Optional[str]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "\Scripts\ariadne-codegen.exe\__main__.py", line 7, in <module>
  File "\Lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\Lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "\Lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\Lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\Lib\site-packages\ariadne_codegen\main.py", line 54, in main
    generated_files = package_generator.generate()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\Lib\site-packages\ariadne_codegen\generators\package.py", line 136, in generate
    self._generate_client()
  File "\Lib\site-packages\ariadne_codegen\generators\package.py", line 219, in _generate_client
    raise ParsingError(f"Argument type {type_} not found in schema.")
ariadne_codegen.exceptions.ParsingError: Argument type Date not found in schema.
```

**Comment by mat-sop** [comment]
Hello @lromanowicz, thank you for creating this issue. It looks like an exception is incorrectly thrown when any custom scalar (in this case `Date`) is used as the operation`s argument type.

**Comment by lromanowicz** [comment]
> Hello @lromanowicz, thank you for creating this issue. It looks like an exception is incorrectly thrown when any custom scalar (in this case `Date`) is used as the operation`s argument type.

PS. Same happens for `DateTime` I believe, but I guess the fix will treat all of these the same way.

**Comment by mat-sop** [comment]
Yes, the fix will solve it for all custom scalars defined in the schema.
